=== eclipse-openj9/openj9/test/TestConfig/playlist.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
  Copyright (c) 2017, 2018 IBM Corp. and others

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] http://openjdk.java.net/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="playlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="include" minOccurs="0"/>
        <xs:element name="test" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:all>
              <xs:element type="xs:string" name="testCaseName"/>
              <xs:element name="variations" minOccurs="0" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="variation" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="command"/>
              <xs:element type="xs:string" name="disabled" minOccurs="0"/>
              <xs:element type="xs:string" name="capabilities" minOccurs="0"/>
              <xs:element type="xs:string" name="platformRequirements" minOccurs="0"/>
              <xs:element name="tags" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="tag" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="levels" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="level" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="groups" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="group" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="impls" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="impl" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="subsets" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="subset" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eclipse-openj9/openj9/test/NativeTest/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright (c) 2016, 2017 IBM Corp. and others

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] http://openjdk.java.net/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
-->

<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../TestConfig/playlist.xsd">

	<test>
		<testCaseName>algotest2</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)algotest' -avltest:$(TEST_RESROOT)$(D)..$(D)algotest$(D)avltest.lst -Xcheck:memory:ignoreUnfreedCallsite=zip/:dbgwrapper:unknown:wrapper; \
	$(TEST_STATUS)</command>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>ctest</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)ctest' ; \
	$(TEST_STATUS)</command>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>jniargtests</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) -Xint \
	-cp $(Q)$(TEST_RESROOT)$(D)jniargtests$(D)jniargtests.jar$(Q) JniArgTests ; \
	$(TEST_STATUS)</command>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>vmtest</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)vmtest'  ; \
	$(TEST_STATUS)</command>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>jsigjnitest</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)jsigjnitest' \
	'$(JAVA_BIN)$(D)j9vm' $(JVM_OPTIONS) ; \
	$(TEST_STATUS)</command>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>gc_rwlocktest</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>chmod u+x $(JAVA_SHARED_LIBRARIES_DIR)$(D)gc_rwlocktest; \
	$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)gc_rwlocktest' -verbose; \
	$(TEST_STATUS)</command>
		<platformRequirements>^os.win</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>gc_rwlocktest_win</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)gc_rwlocktest' -verbose; \
	$(TEST_STATUS)</command>
		<platformRequirements>os.win</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>shrtest_linux_SE90</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl all ; \
	$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)shrtest' $(JVM_OPTIONS)  -Djava.home='$(JAVA_BIN)$(D)..$(D)'  '-Xbootclasspath/a:"dummy1$(P)dummy2$(P)dummy3"' ; \
	$(TEST_STATUS)
	</command>
		<platformRequirements>os.linux</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>shrtest_zos_SE90</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl all zos ; \
	$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)shrtest' $(JVM_OPTIONS)  -Djava.home='$(JAVA_BIN)$(D)..$(D)'  '-Xbootclasspath/a:"dummy1$(P)dummy2$(P)dummy3"' ; \
	$(TEST_STATUS)
	</command>
		<platformRequirements>os.zos</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>shrtest_aix_SE90</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl all aix ; \
	$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)shrtest' $(JVM_OPTIONS)  -Djava.home='$(JAVA_BIN)$(D)..$(D)'  '-Xbootclasspath/a:"dummy1$(P)dummy2$(P)dummy3"' ; \
	$(TEST_STATUS)
	</command>
		<platformRequirements>os.aix</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>shrtest_win_SE90</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)shrtest' $(JVM_OPTIONS)  -Djava.home='$(JAVA_BIN)$(D)..$(D)'  '-Xbootclasspath/a:"dummy1$(P)dummy2$(P)dummy3"' ; \
	$(TEST_STATUS)
	</command>
		<platformRequirements>os.win</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>shrtest_linux_SE80</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl all ; \
	$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)shrtest' $(JVM_OPTIONS)  -Djava.home='$(JAVA_BIN)$(D)..$(D)' ; \
	$(TEST_STATUS)
	</command>
		<platformRequirements>os.linux</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>shrtest_zos_SE80</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl all zos ; \
	$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)shrtest' $(JVM_OPTIONS)  -Djava.home='$(JAVA_BIN)$(D)..$(D)' ; \
	$(TEST_STATUS)
	</command>
		<platformRequirements>os.zos</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>shrtest_aix_SE80</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl all aix ; \
	$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)shrtest' $(JVM_OPTIONS)  -Djava.home='$(JAVA_BIN)$(D)..$(D)'  ; \
	$(TEST_STATUS)
	</command>
		<platformRequirements>os.aix</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>shrtest_win_SE80</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)shrtest' $(JVM_OPTIONS)  -Djava.home='$(JAVA_BIN)$(D)..$(D)'  ; \
	$(TEST_STATUS)
	</command>
		<platformRequirements>os.win</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>thrstatetest</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)thrstatetest' $(JVM_OPTIONS)  -Djava.home='$(JAVA_BIN)$(D)..$(D)' -Dcom.ibm.tools.attach.enable=no -Dibm.java9.forceCommonCleanerShutdown=true ; \
	$(TEST_STATUS)
	</command>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>vmLifecyleTests</testCaseName>
		<variations>
			<variation>Mode110</variation>
			<variation>Mode610</variation>
			<variation>Mode301</variation>
			<variation>Mode351</variation>
			<variation>Mode501</variation>
			<variation>Mode551</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	'$(JAVA_SHARED_LIBRARIES_DIR)$(D)vmLifecyleTests' $(JVM_OPTIONS) -Djava.home='$(JAVA_BIN)$(D)..$(D)' -Dibm.java9.forceCommonCleanerShutdown=true ; \
	$(TEST_STATUS)</command>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
</playlist>

=== eclipse-openj9/openj9/test/functional/cmdLineTests/shareClassTests/ListAllCachesTests/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright (c) 2016, 2019 IBM Corp. and others

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] http://openjdk.java.net/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->

<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../TestConfig/playlist.xsd">
	<test>
		<testCaseName>testSCCMLListALLCaches</testCaseName>
		<variations>
			<variation>Mode110</variation>
			<variation>Mode610</variation>	
		</variations>
		<command>cp $(Q)$(TEST_RESROOT)$(D)ShareClassesCMLTests.jar$(Q) .; \
	$(Q)$(TEST_JDK_HOME)$(D)bin$(D)jar$(EXECUTABLE_SUFFIX)$(Q) xf ShareClassesCMLTests.jar; \
	$(JAVA_COMMAND) $(JVM_OPTIONS) -DJAVA_HOME=$(SQ)$(TEST_JDK_HOME)$(SQ) -DPATHSEP=$(Q)$(D)$(Q) -DCPDL=$(Q)$(P)$(Q) -DRUN_SCRIPT=$(RUN_SCRIPT) -DSCRIPT_SUFFIX=$(SCRIPT_SUFFIX) -DEXECUTABLE_SUFFIX=$(EXECUTABLE_SUFFIX) -DJAVA_EXE=$(SQ)$(JAVA_COMMAND) $(JVM_OPTIONS)$(SQ) -DSCMODE=204 -DTEST_JVM_OPTIONS=$(Q)$(JVM_OPTIONS)$(Q) \
	-jar $(CMDLINETESTER_JAR) \
	-config $(Q)$(TEST_RESROOT)$(D)listAllCachesTests.xml$(Q) -xids all,$(PLATFORM) -xlist $(Q)$(TEST_RESROOT)$(D)exclude.xml$(Q) \
	-nonZeroExitWhenError \
	-outputLimit 300; \
	$(TEST_STATUS)</command>
		<platformRequirements>os.linux,arch.x86</platformRequirements>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<aot>explicit</aot>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>testSCCMLExpireAndListALLCaches</testCaseName>
		<variations>
			<variation>Mode110</variation>
		</variations>
		<command>cp $(Q)$(TEST_RESROOT)$(D)ShareClassesCMLTests.jar$(Q) $(REPORTDIR); \
	$(Q)$(TEST_JDK_HOME)$(D)bin$(D)jar$(EXECUTABLE_SUFFIX)$(Q) xf ShareClassesCMLTests.jar; \
	$(JAVA_COMMAND) $(JVM_OPTIONS) -DJAVA_HOME=$(SQ)$(TEST_JDK_HOME)$(SQ) -DPATHSEP=$(Q)$(D)$(Q) -DCPDL=$(Q)$(P)$(Q) -DRUN_SCRIPT=$(RUN_SCRIPT) -DSCRIPT_SUFFIX=$(SCRIPT_SUFFIX) -DEXECUTABLE_SUFFIX=$(EXECUTABLE_SUFFIX) -DJAVA_EXE=$(SQ)$(JAVA_COMMAND) $(JVM_OPTIONS)$(SQ) -DSCMODE=204 -DTEST_JVM_OPTIONS=$(Q)$(JVM_OPTIONS)$(Q) \
	-jar $(CMDLINETESTER_JAR) \
	-config $(Q)$(TEST_RESROOT)$(D)expireAndListAllCachesTests.xml$(Q) -xids all,$(PLATFORM) -xlist $(Q)$(TEST_RESROOT)$(D)exclude.xml$(Q) \
	-nonZeroExitWhenError \
	-outputLimit 300; \
	$(TEST_STATUS)</command>
		<platformRequirements>os.linux,arch.x86</platformRequirements>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<aot>explicit</aot>

	</test>
</playlist>

=== eclipse-openj9/openj9/test/Jsr292/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright (c) 2016, 2017 IBM Corp. and others

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] http://openjdk.java.net/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->

<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../TestConfig/playlist.xsd">
	<test>
		<testCaseName>jsr292Test_SE80</testCaseName>
		<variations>
			<variation>NoOptions</variation>
			<variation>Mode195</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-Djava.security.policy=$(Q)$(TEST_RESROOT)$(D)java.policy$(Q) \
	-cp $(Q)$(TEST_RESROOT)$(D)jsr292test.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)asm-all.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testngSE80.xml$(Q) \
	-testnames jsr292Test,jsr292Test_optional \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
		</subsets>
	</test>

	<test>
		<testCaseName>jsr292Test_SE90</testCaseName>
		<variations>
			<variation>NoOptions</variation>
			<variation>Mode195</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	--add-opens=java.base/java.lang=ALL-UNNAMED \
	-Djava.security.policy=$(Q)$(TEST_RESROOT)$(D)java.policy$(Q) \
	-cp $(Q)$(TEST_RESROOT)$(D)jsr292test.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)asm-all.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testngSE90.xml$(Q) \
	-testnames jsr292Test,jsr292Test_B95up,jsr292Test_optional \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE90</subset>
		</subsets>
	</test>

	<test>
		<testCaseName>jsr292Test_JitCount0_SE80</testCaseName>
		<variations>
			<variation>-Xjit:count=0</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-Djava.security.policy=$(Q)$(TEST_RESROOT)$(D)java.policy$(Q) \
	-cp $(Q)$(TEST_RESROOT)$(D)jsr292test.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)asm-all.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testngSE80.xml$(Q) \
	-testnames jsr292Test \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<platformRequirements>^arch.arm</platformRequirements>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
		</subsets>
	</test>

	<test>
		<testCaseName>jsr292Test_JitCount0_SE90</testCaseName>
		<variations>
			<variation>-Xjit:count=0</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	--add-opens=java.base/java.lang=ALL-UNNAMED \
	-Djava.security.policy=$(Q)$(TEST_RESROOT)$(D)java.policy$(Q) \
	-cp $(Q)$(TEST_RESROOT)$(D)jsr292test.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)asm-all.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testngSE90.xml$(Q) \
	-testnames jsr292Test,jsr292Test_B95up \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<platformRequirements>^arch.arm</platformRequirements>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE90</subset>
		</subsets>
	</test>

	<test>
		<testCaseName>jsr292BootstrapTest_SE80</testCaseName>
		<variations>
			<variation>NoOptions</variation>
			<variation>Mode195</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-Xbootclasspath/a:$(Q)$(TEST_RESROOT)$(D)jsr292bootstrap.jar$(Q) \
	-cp $(Q)$(TEST_RESROOT)$(D)jsr292test.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testngSE80.xml$(Q) \
	-testnames jsr292BootstrapTest \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
		</subsets>
	</test>

	<test>
		<testCaseName>jsr292BootstrapTest_SE90</testCaseName>
		<variations>
			<variation>NoOptions</variation>
			<variation>Mode195</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	--add-opens=java.base/java.lang=ALL-UNNAMED --add-exports java.base/jdk.internal.reflect=ALL-UNNAMED \
	-Xbootclasspath/a:$(Q)$(TEST_RESROOT)$(D)jsr292bootstrap.jar$(Q) \
	-cp $(Q)$(TEST_RESROOT)$(D)jsr292test.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testngSE90.xml$(Q) \
	-testnames jsr292BootstrapTest \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE90</subset>
		</subsets>
	</test>

	<test>
		<featureIds>
			<featureId>116831</featureId>
		</featureIds>
		<testCaseName>jsr292_MethodHandleAPI_Test</testCaseName>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	--add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED \
	-Djava.security.policy=$(Q)$(TEST_RESROOT)$(D)java.policy$(Q) \
	-cp $(Q)$(TEST_RESROOT)$(D)jsr292test.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)asm-all.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testngSE90.xml$(Q) \
	-testnames jsr292_MethodHandleAPI_Test \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE90</subset>
		</subsets>
	</test>

	<test>
		<featureIds>
			<featureId>116831</featureId>
		</featureIds>
		<testCaseName>jsr292_MethodHandleAPI_Test_JitCount1</testCaseName>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	--add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED \
	-Xjit:count=1,disableAsyncCompilation,verbose,vlog="$(TEST_RESROOT)$(D)jitv.log" \
	-Djava.security.policy=$(Q)$(TEST_RESROOT)$(D)java.policy$(Q) \
	-cp $(Q)$(TEST_RESROOT)$(D)jsr292test.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)asm-all.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testngSE90.xml$(Q) \
	-testnames jsr292_MethodHandleAPI_Test \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE90</subset>
		</subsets>
	</test>

	<test>
		<testCaseName>jsr292_InDynTest</testCaseName>
		<variations>
			<variation>NoOptions</variation>
			<variation>Mode195</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-cp $(Q)$(TEST_RESROOT)$(D)jsr292test.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)asm-all.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng$(JAVA_VERSION).xml$(Q) \
	-testnames jsr292_InDynTest \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>

</playlist>

=== eclipse-openj9/openj9/test/functional/Java14andUp/playlist.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
  Copyright IBM Corp. and others 2020

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] https://openjdk.org/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../TestConfig/playlist.xsd">
	<test>
		<testCaseName>Jep359Tests</testCaseName>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
			--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
            -cp $(Q)$(LIB_DIR)$(D)asm.jar$(P)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(TEST_RESROOT)$(D)GeneralTest.jar$(Q) \
            org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) -testnames Jep359Tests \
            -groups $(TEST_GROUP) \
            -excludegroups $(DEFAULT_EXCLUDE); \
            $(TEST_STATUS)
        </command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>14+</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>ThreadInterruptImplTest</testCaseName>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
            -cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(TEST_RESROOT)$(D)GeneralTest.jar$(Q) \
            org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) -testnames ThreadInterruptImplTest \
            -groups $(TEST_GROUP) \
            -excludegroups $(DEFAULT_EXCLUDE); \
            $(TEST_STATUS)
        </command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>14+</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>JEP358NPEMessageTests</testCaseName>
		<variations>
			<variation>-XX:+ShowCodeDetailsInExceptionMessages --add-exports java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) -DhasDebugInfo=true \
            -cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(TEST_RESROOT)$(D)GeneralTest.jar$(Q) \
            org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) -testnames JEP358NPEMessageTests \
            -groups $(TEST_GROUP) \
            -excludegroups $(DEFAULT_EXCLUDE); \
            $(TEST_STATUS)
        </command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>14+</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>JEP358NPEMessageTests-noDebugInfo</testCaseName>
		<variations>
			<variation>-XX:+ShowCodeDetailsInExceptionMessages --add-exports java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) -DhasDebugInfo=false \
            -cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(TEST_RESROOT)$(D)GeneralTest-noDebugInfo.jar$(Q) \
            org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) -testnames JEP358NPEMessageTests \
            -groups $(TEST_GROUP) \
            -excludegroups $(DEFAULT_EXCLUDE); \
            $(TEST_STATUS)
        </command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>14+</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
</playlist>
